import React, { useState } from 'react';
import { RebalancePlan } from '../../types';
import { Button } from '../ui/Button';
import { Modal } from '../ui/Modal';
import { ArrowRight, CheckCircle, XCircle, Sparkles, ShieldCheck, AlertCircle } from 'lucide-react';

export const RebalancePlanView: React.FC<{ plan: RebalancePlan; onApprove: () => void; onReject: () => void; isExecuting?: boolean }> = ({ plan, onApprove, onReject, isExecuting = false }) => {
  const [showConfirmModal, setShowConfirmModal] = useState(false);
  return <div className="space-y-8 font-sans">
    <div className="architectural-border bg-[#141a32] text-white p-6 md:p-8"><div className="flex items-center gap-3 mb-3"><Sparkles className="w-5 h-5 text-[#497cff]" /><span className="text-xs uppercase font-bold tracking-widest text-[#bfc5e4]">Capacity analysis plan</span></div><h3 className="font-serif text-3xl font-bold mb-3">{plan.team_name} Recommendation</h3><p className="text-sm text-[#bfc5e4] max-w-3xl">{plan.summary}</p><div className="mt-6 pt-4 border-t border-white/15 flex items-center gap-2 text-xs text-[#bfc5e4]"><ShieldCheck className="w-4 h-4 text-green-400" /><span>Manager approval is required before database changes are applied.</span><span className="ml-auto">{new Date(plan.generated_at).toLocaleString()}</span></div></div>
    <div className="grid grid-cols-2 lg:grid-cols-4 gap-4">{[['Overload Reduction', `${plan.expected_impact.overload_reduction_percent}%`], ['Burnout Risk Reduction', `${plan.expected_impact.burnout_risk_reduction_percent}%`], ['Velocity Multiplier', `${plan.expected_impact.velocity_gain_multiplier}x`], ['Cycle Time Saved', `${plan.expected_impact.predicted_cycle_time_savings_days} days`]].map(([label, value]) => <div key={label} className="border border-[#141a32]/15 bg-white p-5"><div className="text-[10px] uppercase tracking-wider text-[#76767e] font-semibold mb-1">{label}</div><div className="font-serif text-3xl font-bold text-[#1b873f]">{value}</div></div>)}</div>
    <div className="border border-[#141a32]/15 bg-white p-6 md:p-8"><h4 className="font-serif text-2xl font-bold text-[#141a32] mb-6">Current vs. Proposed Workload</h4><div className="space-y-6">{plan.member_comparisons.map(member => <div key={member.member_id} className="border border-[#141a32]/15 p-5 bg-[#fcf9f8]"><div className="flex flex-col md:flex-row justify-between gap-4 mb-4"><div><span className="font-serif text-lg font-bold">{member.member_name}</span><span className="text-xs text-[#76767e] ml-2">{member.title}</span></div><div className="flex items-center gap-3 text-sm font-bold"><span>{member.before_hours}h / {member.capacity_hours}h</span><ArrowRight className="w-4 h-4 text-[#497cff]" /><span className="text-[#1b873f]">{member.proposed_hours}h / {member.capacity_hours}h</span></div></div><div className="grid md:grid-cols-2 gap-4"><div><div className="text-[10px] uppercase text-[#76767e] mb-1">Current: {member.before_utilization}%</div><div className="h-3 bg-white border border-[#141a32]/20"><div className="h-full bg-[#141a32]" style={{ width: `${Math.min(member.before_utilization, 100)}%` }} /></div></div><div><div className="text-[10px] uppercase text-[#76767e] mb-1">Proposed: {member.proposed_utilization}%</div><div className="h-3 bg-white border border-[#141a32]/20"><div className="h-full bg-[#1b873f]" style={{ width: `${Math.min(member.proposed_utilization, 100)}%` }} /></div></div></div><div className="mt-3 text-xs text-[#46464d]">{member.proposed_status} (previously {member.before_status})</div></div>)}</div></div>
    <div className="border border-[#141a32]/15 bg-white p-6 md:p-8"><h4 className="font-serif text-2xl font-bold mb-6">Task Reassignments ({plan.shifts.length})</h4>{plan.shifts.length === 0 ? <p className="text-sm text-[#76767e]">No safe task reassignments were found.</p> : <div className="grid md:grid-cols-2 gap-6">{plan.shifts.map(shift => <div key={shift.task_id} className="border border-[#141a32]/15 p-5 bg-[#fcf9f8]"><div className="flex justify-between"><span className="font-mono text-xs font-bold text-[#497cff]">REASSIGN</span><span className="text-xs font-bold bg-[#141a32] text-white px-2 py-0.5">{shift.hours}h</span></div><h5 className="font-serif text-lg font-bold mt-2">{shift.task_title}</h5><p className="text-xs text-[#46464d] leading-relaxed my-4">{shift.reason}</p><div className="pt-3 border-t border-[#141a32]/10 flex justify-between text-xs font-semibold"><span className="text-[#ba1a1a]">{shift.from_member_name}</span><ArrowRight className="w-4 h-4" /><span className="text-[#1b873f]">{shift.to_member_name}</span></div></div>)}</div>}</div>
    <div className="border-t-2 border-[#141a32] pt-6 flex flex-col sm:flex-row justify-between items-center gap-4 bg-[#f6f3f2] p-6"><div className="text-xs text-[#46464d] flex items-center gap-2"><AlertCircle className="w-4 h-4 text-[#497cff]" /><span>Approving applies the listed task assignments to the database.</span></div><div className="flex gap-3"><Button variant="secondary" size="md" onClick={onReject} disabled={isExecuting} leftIcon={<XCircle className="w-4 h-4" />}>Reject Plan</Button><Button variant="primary" size="md" onClick={() => setShowConfirmModal(true)} isLoading={isExecuting} leftIcon={<CheckCircle className="w-4 h-4" />}>Approve Changes</Button></div></div>
    <Modal isOpen={showConfirmModal} onClose={() => setShowConfirmModal(false)} title="Authorize Workload Changes" subtitle={`${plan.team_name} • ${plan.shifts.reduce((total, shift) => total + shift.hours, 0)} hours affected`}><div className="space-y-4"><p className="text-sm text-[#46464d]">The following persisted task assignments will be updated:</p><ul className="space-y-2 text-xs bg-[#f0eded] p-4">{plan.shifts.map(shift => <li key={shift.task_id} className="flex gap-2"><CheckCircle className="w-4 h-4 text-[#1b873f] shrink-0" /><span>{shift.task_title}: {shift.from_member_name} to {shift.to_member_name}</span></li>)}</ul><div className="flex justify-end gap-3 border-t pt-4"><Button variant="outline" size="sm" onClick={() => setShowConfirmModal(false)}>Cancel</Button><Button variant="primary" size="sm" onClick={() => { setShowConfirmModal(false); onApprove(); }}>Confirm & Apply</Button></div></div></Modal>
  </div>;
};
